version: "3.6"
services:
    db:
        image: postgres:11-alpine
        expose:
            - "5432"
        ports:
            - 5432:5432
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - ./var/pgdata:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: user
            POSTGRES_DB: db_name
    php-cli:
        build:
            context: docker/php-cli
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www
    php-fpm:
        build:
            context: docker/php-fpm
            dockerfile: Dockerfile
        expose:
          - 9000
        restart: always
        volumes:
            - ./:/var/www

    rpc-fpm:
        build:
            context: ../rpc/docker/php-fpm
            dockerfile: Dockerfile
        expose:
          - 9000
        restart: always
        volumes:
            - ../rpc/:/var/www
    rpc-cli:
        build:
            context: ../rpc/docker/php-cli
            dockerfile: Dockerfile
        volumes:
            - ../rpc/:/var/www

    nginx:
        build:
            context: docker/nginx
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./:/var/www
        depends_on:
            - php-fpm
            - rpc-fpm
        ports:
            - 80:8080
            - 8081:8081
